#pragma once

typedef enum RSTATUS_ {
	RSTATUS_OK = 0,
	RSTATUS_MEM_ALLOC_FAILED,
	RSTATUS_OPEN_FILE_ERROR,
	RSTATUS_WINDOW_ERROR,
	RSTATUS_CONTEXT_ERROR,
	RSTATUS_CHOOSE_VISUAL_ERROR,
	RSTATUS_MAKE_CURRENT_ERROR


} RSTATUS;